---
Title : Classification de l'Audio, Premiers tests  
Author : Dmitrašinović Théotime  
**But** :  
1. Application des modèles de Classification suivants:
  - Gradient Boosting
  - SVC
  - OneVsRest
  - petit réseau neuronal
2. Sur deux types de dataset:
  - corpus normal
  - sur samplé pour les classes minoritaires
  - sous samplé pour education
3. Puis Affichage des scores et matrice de confusions  


---

# Google Drive Mount

In [4]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


# Classification des embeddings audio


## Recup data

In [8]:
import pickle
import pandas as pd
# Les datasets labels
DataSetsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/DataSets/"

train = pd.read_csv(DataSetsPath + "Train_SurSampling1.csv")
test = pd.read_csv(DataSetsPath + "Test_SurSampling1.csv")
val = pd.read_csv(DataSetsPath + "Val_SurSampling1.csv")

# Les embeddings Audio
AudioEmbeddingsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Embeddings/Audio_Embeddings/Tests_Audio_Embeddings/all_embeddings_Average_ALL.pkl"
with open(AudioEmbeddingsPath, "rb") as fp:
    embeddings = pickle.load(fp)
df_embes = pd.DataFrame.from_dict((embeddings), orient='index')
df_embes


0         1         2         3         4         5    \
-AZS5cgybKcI -0.284029  0.032755  0.318786 -0.508630 -0.158374 -0.537420   
-uSTNyHkde08 -0.151631  0.126783  0.009415 -0.808152 -0.167872 -0.080102   
-lvK2TPBDvl4 -0.098593 -0.052491 -0.110585 -0.009614  0.013139 -0.133422   
-OT8lw1Rl-WM -0.333148 -0.167473  0.068600  1.011651 -0.096846 -0.342634   
-u9hauSrihYQ  0.079280 -0.028590 -0.016004 -0.681075  0.094331 -0.406785   
...                ...       ...       ...       ...       ...       ...   
-7aXpBF2mjtg -0.773474  0.042919  0.213763 -0.100454 -0.162294 -0.664950   
-2REkk9SCRn0 -0.455301  0.143603  0.248981 -0.493621 -0.125186 -0.466236   
-g4woIrtHTOc  0.234583 -0.146714  0.144448 -0.608542 -0.040591 -0.017545   
-pQu3dufotPM  0.446314 -0.173032 -0.054157 -0.816151  0.147513 -0.476856   
-8BbZTCdB2X4 -0.111468 -0.024730  0.091311 -1.111181  0.160816 -0.030962   

                   6         7         8         9    ...       118       119  \
-AZS5cgybKcI -0.272469 -0.247939 -0.489918 -0.421043  ... -0.750526  0.275620   
-uSTNyHkde08 -0.276894 -0.163420 -0.419045 -0.328050  ... -0.845796  0.426595   
-lvK2TPBDvl4 -0.167703 -0.178163 -0.333957 -0.176832  ... -0.369331  0.103513   
-OT8lw1Rl-WM -0.379832  0.075960 -0.371182 -0.500207  ... -0.173641  0.186639   
-u9hauSrihYQ -0.167358 -0.368698 -0.669618 -0.474807  ... -1.293931  0.272565   
...                ...       ...       ...       ...  ...       ...       ...   
-7aXpBF2mjtg -0.160105 -0.114828 -0.070436 -0.418116  ...  0.093300  0.097024   
-2REkk9SCRn0 -0.150589 -0.059695 -0.243468 -0.422684  ... -0.461478  0.290586   
-g4woIrtHTOc -0.325585 -0.218888 -0.377796 -0.605836  ... -0.701620  0.615627   
-pQu3dufotPM -0.208783 -0.315753 -0.592461 -0.386252  ... -1.233094  0.179424   
-8BbZTCdB2X4 -0.213986  0.054619 -0.664884 -0.553732  ... -1.133428  0.726648   

                   120       121       122       123       124       125  \
-AZS5cgybKcI  0.006835 -0.046609  0.047074  0.087500 -0.190523 -0.319955   
-uSTNyHkde08 -0.251827 -0.044944  0.011121 -0.121799  0.044923  0.382124   
-lvK2TPBDvl4 -0.143293  0.129252 -0.105773 -0.048344  0.353802  0.061697   
-OT8lw1Rl-WM -0.098925 -0.267119 -0.397092 -0.148772  0.067599 -0.249984   
-u9hauSrihYQ -0.074230  0.400362 -0.154907 -0.062980  0.478865  0.338979   
...                ...       ...       ...       ...       ...       ...   
-7aXpBF2mjtg -0.207285  0.019760 -0.348485  0.093414  0.099416 -0.617643   
-2REkk9SCRn0 -0.061957 -0.002654 -0.140968  0.111998 -0.098295 -0.463974   
-g4woIrtHTOc -0.080431  0.205240 -0.356296  0.428355  0.665380 -0.142507   
-pQu3dufotPM -0.232642  0.440303 -0.206396  0.095516  0.964520  0.211571   
-8BbZTCdB2X4 -0.197316 -0.044306 -0.162641 -0.150747  0.291398  0.067090   

                   126       127  
-AZS5cgybKcI  0.313330 -0.104647  
-uSTNyHkde08  0.337639 -0.112781  
-lvK2TPBDvl4  0.225367  0.045655  
-OT8lw1Rl-WM -0.066723 -0.206089  
-u9hauSrihYQ  0.541409 -0.225783  
...                ...       ...  
-7aXpBF2mjtg  0.297150  0.345990  
-2REkk9SCRn0  0.320818  0.377544  
-g4woIrtHTOc  0.069681 -0.214658  
-pQu3dufotPM  0.271776 -0.265754  
-8BbZTCdB2X4  0.303224 -0.166869  

[2280 rows x 128 columns]

In [9]:
import plotly.express as px
px.pie(train, names="label", title="Distribution des catégories Youtube")

In [10]:
train = train.set_index('name').join(df_embes)
test = test.set_index('name').join(df_embes)
val = val.set_index('name').join(df_embes)

In [11]:
train

label         0         1         2         3  \
--6rP8FO_Vwc         People & Blogs -0.166694  0.050484  0.253511 -0.809449   
--7-quPaRol8   Science & Technology  0.633001 -0.379534 -0.056173 -0.925263   
--85-j7Nr9i4              Education -0.480638 -0.044714  0.271230 -0.321938   
--8qvGAWiPQY  Nonprofits & Activism -0.222524  0.094968  0.119695 -1.092793   
--8qvGAWiPQY  Nonprofits & Activism -0.222524  0.094968  0.119695 -1.092793   
...                             ...       ...       ...       ...       ...   
-zgg9jE1jXjg                 Sports -0.511622  0.066183  0.252751 -0.400739   
-zi5ISjgijko         People & Blogs  0.819803 -0.398105 -0.173367 -0.826518   
-zkCoaPOsw5U         People & Blogs -0.492590  0.079372  0.197810 -0.396203   
-znxRGH92XDg       Film & Animation -0.367281  0.388813  0.125710 -0.765032   
-zywWM3J3i8M       Film & Animation  0.379299 -0.138963  0.343662 -0.780760   

                     4         5         6         7         8  ...       118  \
--6rP8FO_Vwc -0.013224 -0.240518 -0.068054 -0.523857 -0.260299  ... -0.959462   
--7-quPaRol8 -0.200088 -0.462940 -0.438933 -0.503821 -0.601142  ... -1.005463   
--85-j7Nr9i4  0.304537 -0.473229 -0.009028  0.834463 -0.291670  ... -0.079489   
--8qvGAWiPQY  0.468928  0.235932  0.054821 -0.333084 -0.548071  ... -0.888544   
--8qvGAWiPQY  0.468928  0.235932  0.054821 -0.333084 -0.548071  ... -0.888544   
...                ...       ...       ...       ...       ...  ...       ...   
-zgg9jE1jXjg  0.149225 -0.482930  0.037917 -0.263113 -0.325619  ... -0.133399   
-zi5ISjgijko -0.203872 -0.307542 -0.533315 -0.300021 -0.549575  ... -0.975516   
-zkCoaPOsw5U -0.012919 -0.471123 -0.016498  0.336613 -0.187519  ... -0.040631   
-znxRGH92XDg -0.244954 -0.720479 -0.203410 -0.431310 -0.547694  ... -1.100536   
-zywWM3J3i8M  0.037193 -0.224478 -0.296797 -0.387957 -0.548740  ... -0.925175   

                   119       120       121       122       123       124  \
--6rP8FO_Vwc  0.138230  0.109616  0.254651 -0.109181  0.000126 -0.040322   
--7-quPaRol8  0.127230 -0.176327  0.173122 -0.373853  0.605131  0.702665   
--85-j7Nr9i4  0.152340 -0.232249 -0.075989 -0.464088 -0.143563  0.033672   
--8qvGAWiPQY  0.272699 -0.219627  0.280659 -0.264636 -0.271978 -0.040519   
--8qvGAWiPQY  0.272699 -0.219627  0.280659 -0.264636 -0.271978 -0.040519   
...                ...       ...       ...       ...       ...       ...   
-zgg9jE1jXjg -0.071612 -0.124187  0.078400 -0.121180  0.000225 -0.165718   
-zi5ISjgijko  0.036172 -0.117929 -0.039117 -0.317645  0.694522  0.722401   
-zkCoaPOsw5U  0.066115 -0.063387 -0.050204 -0.264435  0.041060  0.010680   
-znxRGH92XDg  0.327990 -0.001546  0.251915  0.046247 -0.000701 -0.181923   
-zywWM3J3i8M  0.106157 -0.196180  0.002303 -0.202235  0.206169 -0.038322   

                   125       126       127  
--6rP8FO_Vwc -0.054456  0.571680  0.054407  
--7-quPaRol8 -0.039136 -0.174976 -0.351537  
--85-j7Nr9i4 -0.557218  0.134749 -0.073850  
--8qvGAWiPQY -0.056831  0.393632 -0.054731  
--8qvGAWiPQY -0.056831  0.393632 -0.054731  
...                ...       ...       ...  
-zgg9jE1jXjg -0.380529  0.529981  0.252555  
-zi5ISjgijko  0.322798 -0.122459 -0.322128  
-zkCoaPOsw5U -0.543131  0.091265 -0.045513  
-znxRGH92XDg -0.337185  0.342117  0.240402  
-zywWM3J3i8M  0.136169  0.282073 -0.236374  

[1909 rows x 129 columns]

## Classifieur


### Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
y_train = train.label
X_train = train.drop(columns=['label'])

y_test = test.label
X_test = test.drop(columns=['label'])

In [ ]:
y_train

--6rP8FO_Vwc           People & Blogs
--7-quPaRol8     Science & Technology
--85-j7Nr9i4                Education
--8qvGAWiPQY    Nonprofits & Activism
--8qvGAWiPQY    Nonprofits & Activism
                        ...          
-zgg9jE1jXjg                   Sports
-zi5ISjgijko           People & Blogs
-zkCoaPOsw5U           People & Blogs
-znxRGH92XDg         Film & Animation
-zywWM3J3i8M         Film & Animation
Name: label, Length: 1909, dtype: object

In [ ]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.01, max_depth=4, random_state=0)
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.3453125

### SVC sur Audio Embe de VGGish

#### Test sur DataSet equilibré 1

In [ ]:
import pickle
import pandas as pd
# Les datasets labels
DataSetsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/DataSets/"

train = pd.read_csv(DataSetsPath + "Train_SurSampling1.csv")
test = pd.read_csv(DataSetsPath + "Test_SurSampling1.csv")
val = pd.read_csv(DataSetsPath + "Val_SurSampling1.csv")

# Les embeddings Audio
AudioEmbeddingsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Audio_Embeddings/Tests_Audio_Embeddings/all_embeddings_Average_ALL.pkl"
with open(AudioEmbeddingsPath, "rb") as fp:
    embeddings = pickle.load(fp)
df_embes = pd.DataFrame.from_dict((embeddings), orient='index')

# DataSet Separation
train = train.set_index('name').join(df_embes)
test = test.set_index('name').join(df_embes)
val = val.set_index('name').join(df_embes)

y_train = train.label
X_train = train.drop(columns=['label'])

y_test = test.label
X_test = test.drop(columns=['label'])

In [ ]:
len(train)

1909

In [ ]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)
pred = clf.predict(X_test)

In [ ]:
clf.score(X_test, y_test)

0.4203125

##### oneVsRest

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
clf = make_pipeline(StandardScaler(), OneVsRestClassifier(SVC(gamma='auto')))
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('onevsrestclassifier',
                 OneVsRestClassifier(estimator=SVC(gamma='auto')))])

In [ ]:
clf.score(X_test, y_test)

0.4109375

#### Test sur dataset non équilibré

In [ ]:
from sklearn.model_selection import train_test_split
def split_TTV(df):
  # Split the data into train, test, and validation sets while maintaining the class distribution
  # Adjust the test_size and random_state parameters as needed
  train, temp = train_test_split(df, train_size=0.6, stratify=df.label, random_state=42)
  test, val = train_test_split(temp, test_size=0.5, stratify=temp.label, random_state=42)

  # You can access the subsets like this
  print("Training set:", train.shape)
  print("Testing set:", test.shape)
  print("Validation set:", val.shape)

  return train, test, val

# Individus Labélisés
CSVLabelisedDataPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/indice_vid_labelled.csv"
df = pd.read_csv(CSVLabelisedDataPath)
train, test, val = split_TTV(df)


# Les embeddings Audio
AudioEmbeddingsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Audio_Embeddings/Tests_Audio_Embeddings/all_embeddings_Average_ALL.pkl"
with open(AudioEmbeddingsPath, "rb") as fp:
    embeddings = pickle.load(fp)
df_embes = pd.DataFrame.from_dict((embeddings), orient='index')

# DataSet Separation
train = train.set_index('name').join(df_embes)
test = test.set_index('name').join(df_embes)
val = val.set_index('name').join(df_embes)

y_train = train.label
X_train = train.drop(columns=['label'])

y_test = test.label
X_test = test.drop(columns=['label'])


Training set: (1368, 2)
Testing set: (456, 2)
Validation set: (456, 2)


In [ ]:
len(train)+len(test)+len(val)

2280

In [ ]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [ ]:
pred = clf.predict(X_test)

In [ ]:
clf.score(X_test, y_test)

0.5087719298245614

##### oneVsRest

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
clf = make_pipeline(StandardScaler(), OneVsRestClassifier(SVC(gamma='auto')))
clf.fit(X_train, y_train)


Pipeline(steps=[('standardscaler', StandardScaler()),
                ('onevsrestclassifier',
                 OneVsRestClassifier(estimator=SVC(gamma='auto')))])

In [ ]:
clf.score(X_test, y_test)

0.506578947368421

#### Test sur dataset sous samplé pour education

In [13]:
from sklearn.model_selection import train_test_split
def split_TTV(df):
  # Split the data into train, test, and validation sets while maintaining the class distribution
  # Adjust the test_size and random_state parameters as needed
  train, temp = train_test_split(df, train_size=0.6, stratify=df.label, random_state=42)
  test, val = train_test_split(temp, test_size=0.5, stratify=temp.label, random_state=42)

  # You can access the subsets like this
  print("Training set:", train.shape)
  print("Testing set:", test.shape)
  print("Validation set:", val.shape)

  return train, test, val

# Individus Labélisés
CSVLabelisedDataPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/indice_vid_labelled.csv"
df = pd.read_csv(CSVLabelisedDataPath)
# on supprime la moitié des individus avec label Education car sûr représentés
subset_to_del = df[df['label']=="Education"].sample(len(df[df['label']=="Education"])//2)
df = df.drop(subset_to_del.index)

train, test, val = split_TTV(df)


# Les embeddings Audio
AudioEmbeddingsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Embeddings/Audio_Embeddings/Tests_Audio_Embeddings/all_embeddings_Average_ALL.pkl"
with open(AudioEmbeddingsPath, "rb") as fp:
    embeddings = pickle.load(fp)
df_embes = pd.DataFrame.from_dict((embeddings), orient='index')

# DataSet Separation
train = train.set_index('name').join(df_embes)
test = test.set_index('name').join(df_embes)
val = val.set_index('name').join(df_embes)

y_train = train.label
X_train = train.drop(columns=['label'])

y_test = test.label
X_test = test.drop(columns=['label'])
print('total:', len(train)+len(test)+len(val))

Training set: (1148, 2)
Testing set: (383, 2)
Validation set: (383, 2)
total: 1914


In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def get_distrib(df, labels):
  label_count = df.label.value_counts()
  return [label_count[k] for k in labels]

def show_distrib(df, train, test, val):
  labels = df.label.unique()
  # Figures
  fig = make_subplots(rows=1, cols=4,
                      specs=[[{"type": "domain"}, {"type": "domain"},
                      {"type": "domain"}, {"type": "domain"}]],
                      subplot_titles=['Original', 'Train', 'Test', 'Validation'])

  fig.add_trace(go.Pie(labels=labels, values=get_distrib(df, labels), scalegroup='one'), 1, 1)
  fig.add_trace(go.Pie(labels=labels, values=get_distrib(train, labels), scalegroup='one'), 1, 2)
  fig.add_trace(go.Pie(labels=labels, values=get_distrib(test, labels), scalegroup='one'), 1, 3)
  fig.add_trace(go.Pie(labels=labels, values=get_distrib(val, labels), scalegroup='one'), 1, 4)

  fig.update_layout(title_text='Distribution des catégories Youtube des différents datasets')
  fig.show()

In [ ]:
show_distrib(df, train, test, val)

In [ ]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [ ]:
pred = clf.predict(X_test)

In [ ]:
clf.score(X_test, y_test)

0.4308093994778068

In [ ]:
from sklearn.metrics import confusion_matrix
list_cat= list(set(y_test))
conf_matrix = confusion_matrix(y_test, pred, labels=list_cat)
print(conf_matrix)

[[ 0  0  0  0  1  1  6  0  0  0  0  3  0  0  0]
 [ 0  3  0  1  0  8  1  0  0  0  0  6  0  0  0]
 [ 0  0  3  4  1  5  2  0  0  0  0  4  0  0  0]
 [ 0  0  0 28  3 11 11  0  0  1  0  5  0  0  1]
 [ 0  0  0  0 14  4  0  0  0  0  0  9  0  0  0]
 [ 0  2  0  3  3 31  8  0  0  0  0 21  0  0  0]
 [ 0  0  0 15  0  1 37  0  0  0  0  4  0  0  0]
 [ 0  0  0  3  1  0  0  0  0  0  0  6  0  0  0]
 [ 0  0  0  0  0  2  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  2  1  3  2  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  4 15  4  0  0  0  0 48  0  0  1]
 [ 0  0  0  0  2  3  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  2  0  0  1  0  0  0  0  1  0  0  0]
 [ 0  0  0  3  3  4  1  0  0  0  0  1  0  0  1]]


In [ ]:
cf = [[i/sum(ligne) for i in ligne] for ligne in conf_matrix]

In [ ]:
len(X_test)

383

In [ ]:
import plotly.express as px
data = cf
fig = px.imshow(data,
                labels=dict(y="Vrai Catégorie", x="Catégorie prédite", color="Productivity"),
                x=list_cat,
                y=list_cat
               )
fig.update_xaxes(side="top")
fig.show()

In [ ]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test, pred)
print(class_report)

                       precision    recall  f1-score   support

     Autos & Vehicles       0.00      0.00      0.00         3
               Comedy       1.00      0.16      0.27        19
            Education       0.44      0.66      0.52        73
        Entertainment       0.46      0.47      0.46        60
     Film & Animation       0.50      0.65      0.56        57
               Gaming       0.00      0.00      0.00         4
        Howto & Style       0.42      0.52      0.47        27
                Music       0.00      0.00      0.00         8
      News & Politics       0.00      0.00      0.00        10
Nonprofits & Activism       0.50      0.16      0.24        19
       People & Blogs       0.34      0.46      0.39        68
       Pets & Animals       0.00      0.00      0.00        11
 Science & Technology       0.33      0.08      0.12        13
               Sports       0.00      0.00      0.00         4
      Travel & Events       0.00      0.00      0.00  

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [ ]:
from sklearn.metrics import accuracy_score
for class_label in set(y_test):
    class_accuracy = accuracy_score(y_test[y_test == class_label], pred[y_test == class_label])
    print(f'Accuracy for class {class_label}: {class_accuracy:.2f}')


Accuracy for class Pets & Animals: 0.00
Accuracy for class Nonprofits & Activism: 0.16
Accuracy for class Comedy: 0.16
Accuracy for class Entertainment: 0.47
Accuracy for class Howto & Style: 0.52
Accuracy for class People & Blogs: 0.46
Accuracy for class Film & Animation: 0.65
Accuracy for class News & Politics: 0.00
Accuracy for class Autos & Vehicles: 0.00
Accuracy for class Music: 0.00
Accuracy for class Sports: 0.00
Accuracy for class Education: 0.66
Accuracy for class Travel & Events: 0.00
Accuracy for class Gaming: 0.00
Accuracy for class Science & Technology: 0.08


In [ ]:
set(y_test)

{'Autos & Vehicles',
 'Comedy',
 'Education',
 'Entertainment',
 'Film & Animation',
 'Gaming',
 'Howto & Style',
 'Music',
 'News & Politics',
 'Nonprofits & Activism',
 'People & Blogs',
 'Pets & Animals',
 'Science & Technology',
 'Sports',
 'Travel & Events'}

In [ ]:
pred

array(['Howto & Style', 'Entertainment', 'People & Blogs', 'Education',
       'People & Blogs', 'Entertainment', 'People & Blogs', 'Education',
       'Entertainment', 'Film & Animation', 'People & Blogs',
       'Film & Animation', 'Film & Animation', 'People & Blogs',
       'Film & Animation', 'Film & Animation', 'Education',
       'Entertainment', 'Entertainment', 'Education', 'People & Blogs',
       'People & Blogs', 'Entertainment', 'Entertainment',
       'People & Blogs', 'Education', 'Education', 'People & Blogs',
       'Film & Animation', 'Entertainment', 'Entertainment',
       'Howto & Style', 'Howto & Style', 'Entertainment', 'Education',
       'People & Blogs', 'People & Blogs', 'Education', 'Education',
       'Education', 'Howto & Style', 'Film & Animation', 'Entertainment',
       'Education', 'Education', 'Education', 'Entertainment',
       'Entertainment', 'Film & Animation', 'Film & Animation',
       'Film & Animation', 'Entertainment', 'Film & Animation',
  

### SVC sur Audio Pred de YAMNet

#### Test sur DataSet equilibré 1

In [ ]:

import pickle
import pandas as pd
# Les datasets labels
DataSetsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/DataSets/"

train = pd.read_csv(DataSetsPath + "Train_SurSampling1.csv")
test = pd.read_csv(DataSetsPath + "Test_SurSampling1.csv")
val = pd.read_csv(DataSetsPath + "Val_SurSampling1.csv")

# Les embeddings Audio
predPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Audio_Embeddings/YAMNet/ALL_predictions_YAMNet.pkl"
with open(predPath, "rb") as fp:
    predictions = pickle.load(fp)
df_pred = pd.DataFrame.from_dict((predictions), orient='index')


# DataSet Separation
train = train.set_index('name').join(df_pred)
test = test.set_index('name').join(df_pred)
val = val.set_index('name').join(df_pred)

y_train = train.label
X_train = train.drop(columns=['label'])

y_test = test.label
X_test = test.drop(columns=['label'])

y_val = val.label
X_val = val.drop(columns=['label'])

In [ ]:
df_pred

0         1             2         3             4    \
-AZS5cgybKcI  0.025266  0.001835  1.925003e-04  0.000397  1.446317e-04   
-uSTNyHkde08  0.901550  0.000252  1.308382e-03  0.016251  9.275483e-07   
-lvK2TPBDvl4  0.289680  0.000088  1.798792e-03  0.003571  4.857006e-08   
-OT8lw1Rl-WM  0.000165  0.000019  1.042128e-06  0.000027  1.152583e-09   
-u9hauSrihYQ  0.873961  0.000537  5.590712e-03  0.019910  2.669240e-05   
...                ...       ...           ...       ...           ...   
-7aXpBF2mjtg  0.000198  0.000004  6.313921e-07  0.000009  2.222242e-10   
-2REkk9SCRn0  0.016435  0.000499  1.121820e-04  0.000277  4.467005e-05   
-g4woIrtHTOc  0.503371  0.001570  2.650695e-03  0.013245  5.734666e-06   
-pQu3dufotPM  0.948938  0.000963  1.105974e-02  0.016475  1.078703e-05   
-8BbZTCdB2X4  0.823550  0.002822  9.281789e-03  0.023985  3.303707e-05   

                   5             6             7             8    \
-AZS5cgybKcI  0.000072  4.624372e-05  4.732015e-06  3.638251e-05   
-uSTNyHkde08  0.021930  2.495787e-05  8.117040e-07  2.121147e-05   
-lvK2TPBDvl4  0.000229  1.813735e-06  7.948588e-08  1.241068e-06   
-OT8lw1Rl-WM  0.000005  1.747444e-08  4.968363e-12  5.525666e-09   
-u9hauSrihYQ  0.000472  6.581184e-05  2.157791e-06  7.214768e-05   
...                ...           ...           ...           ...   
-7aXpBF2mjtg  0.000005  9.458382e-06  3.512658e-08  3.595870e-06   
-2REkk9SCRn0  0.000045  6.285003e-05  3.551395e-06  5.236510e-05   
-g4woIrtHTOc  0.000275  6.412073e-06  3.957370e-08  3.304207e-06   
-pQu3dufotPM  0.000761  1.136992e-05  4.609679e-07  7.582129e-06   
-8BbZTCdB2X4  0.006549  1.204783e-05  2.195528e-07  7.818506e-06   

                       9    ...           511           512           513  \
-AZS5cgybKcI  1.735417e-06  ...  4.330092e-05  9.821250e-07  1.839629e-04   
-uSTNyHkde08  4.280596e-07  ...  1.431625e-05  1.749882e-06  5.454943e-05   
-lvK2TPBDvl4  3.755787e-08  ...  2.261237e-07  7.088843e-10  5.419458e-08   
-OT8lw1Rl-WM  1.668432e-12  ...  1.326842e-05  1.014781e-08  5.257566e-08   
-u9hauSrihYQ  1.203631e-06  ...  2.459629e-06  2.274370e-07  1.540807e-05   
...                    ...  ...           ...           ...           ...   
-7aXpBF2mjtg  9.238269e-08  ...  2.260958e-05  7.437294e-10  3.508532e-06   
-2REkk9SCRn0  2.508292e-06  ...  7.062811e-06  2.063451e-06  3.393742e-05   
-g4woIrtHTOc  3.486264e-08  ...  5.720985e-06  1.885902e-08  1.986428e-08   
-pQu3dufotPM  2.589666e-07  ...  1.025157e-06  1.184329e-07  6.000910e-07   
-8BbZTCdB2X4  7.931755e-08  ...  4.776082e-06  1.639825e-06  1.191597e-06   

                       514           515           516           517  \
-AZS5cgybKcI  5.289807e-04  2.474351e-05  7.315379e-05  1.748715e-04   
-uSTNyHkde08  3.374542e-04  1.035530e-04  3.252637e-05  1.793257e-04   
-lvK2TPBDvl4  3.762583e-07  2.553923e-08  2.225540e-08  6.532983e-08   
-OT8lw1Rl-WM  9.533384e-08  5.398527e-10  6.021600e-08  1.187875e-08   
-u9hauSrihYQ  1.419609e-04  6.659506e-05  6.534895e-06  1.155913e-05   
...                    ...           ...           ...           ...   
-7aXpBF2mjtg  3.261856e-07  2.932347e-10  4.832601e-07  3.888806e-07   
-2REkk9SCRn0  1.259191e-04  4.296944e-06  8.703074e-03  2.638522e-05   
-g4woIrtHTOc  2.641852e-07  1.540977e-08  9.366641e-08  1.067836e-07   
-pQu3dufotPM  2.608112e-06  1.913772e-07  3.376322e-07  2.451204e-07   
-8BbZTCdB2X4  1.210299e-06  1.260052e-07  2.406209e-06  1.841089e-07   

                   518       519           520  
-AZS5cgybKcI  0.001129  0.000285  7.037500e-05  
-uSTNyHkde08  0.000465  0.001299  5.271555e-06  
-lvK2TPBDvl4  0.000013  0.000018  1.035225e-08  
-OT8lw1Rl-WM  0.000007  0.000010  7.441545e-10  
-u9hauSrihYQ  0.000170  0.000153  3.343296e-05  
...                ...       ...           ...  
-7aXpBF2mjtg  0.003454  0.000101  4.476325e-07  
-2REkk9SCRn0  0.001168  0.000189  4.278257e-05  
-g4woIrtHTOc  0.000268  0.000078  7.340961e-08  
-pQu3dufotPM  0.000166  0.000434 

In [ ]:
len(train)

1909

In [ ]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
print(clf.score(X_test, y_test))

0.3078125


In [ ]:
from sklearn.metrics import confusion_matrix
list_cat= list(set(y_test))
conf_matrix = confusion_matrix(y_test, pred, labels=list_cat)
cf = [[i/sum(ligne) for i in ligne] for ligne in conf_matrix]
print(conf_matrix)

[[  0   0   0  27   0   0   0   0   0   0   0   0   0   1   0]
 [  0   1   0  12   0   0   0   3   0   0   0   0   7   5   0]
 [  0   0   0  14   0   0   0   1   0   0   0   0   1  12   0]
 [  0   3   0 139   0   0   0   1   0   0   0   0   0   4   0]
 [  0   0   0   9   0  13   0   0   0   0   0   0   0   6   0]
 [  0   0   0  14   0  10   0   0   0   0   4   0   0   0   0]
 [  0   0   0  20   0   0   0   8   0   0   0   0   0   0   0]
 [  0   1   0  26   0   0   1  26   0   0   0   0   0   3   0]
 [  0   0   0  22   0   0   0   4   0   0   0   0   0   2   0]
 [  0   0   0  22   0   0   0   3   0   0   0   0   0   3   0]
 [  0   1   0  53   0   0   0   5   0   0   1   0   3   5   0]
 [  0   0   0  12   0   0   0   0   0   0  10   0   0   6   0]
 [  0   2   0  22   0   0   0   0   0   0   1   0   3   0   0]
 [  0   0   0  29   1   0   0  10   0   0   2   0   0  17   1]
 [  0   0   0  23   0   2   0   0   0   0   2   0   0   1   0]]


In [ ]:
import plotly.express as px
data = cf
fig = px.imshow(data,
                labels=dict(y="Vrai Catégorie", x="Catégorie prédite", color="Productivity"),
                x=list_cat,
                y=list_cat
               )
fig.update_xaxes(side="top")
fig.show()

##### oneVsRest

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
clf = make_pipeline(StandardScaler(), OneVsRestClassifier(SVC(gamma='auto')))
clf.fit(X_train, y_train)
print(clf.score(X_test, y_test))

0.30625


### Petit réseau neuronal sur YAMNet

In [ ]:
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 28.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 40.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 65.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 70.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 38.0 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=e4f231a9db20f261d4293c6ea23b3c953399722dbb8e6586493f293c8564e9f3
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [ ]:
!pip install transformers

In [ ]:
df_pred

0         1             2         3             4    \
-AZS5cgybKcI  0.025266  0.001835  1.925003e-04  0.000397  1.446317e-04   
-uSTNyHkde08  0.901550  0.000252  1.308382e-03  0.016251  9.275483e-07   
-lvK2TPBDvl4  0.289680  0.000088  1.798792e-03  0.003571  4.857006e-08   
-OT8lw1Rl-WM  0.000165  0.000019  1.042128e-06  0.000027  1.152583e-09   
-u9hauSrihYQ  0.873961  0.000537  5.590712e-03  0.019910  2.669240e-05   
...                ...       ...           ...       ...           ...   
-7aXpBF2mjtg  0.000198  0.000004  6.313921e-07  0.000009  2.222242e-10   
-2REkk9SCRn0  0.016435  0.000499  1.121820e-04  0.000277  4.467005e-05   
-g4woIrtHTOc  0.503371  0.001570  2.650695e-03  0.013245  5.734666e-06   
-pQu3dufotPM  0.948938  0.000963  1.105974e-02  0.016475  1.078703e-05   
-8BbZTCdB2X4  0.823550  0.002822  9.281789e-03  0.023985  3.303707e-05   

                   5             6             7             8    \
-AZS5cgybKcI  0.000072  4.624372e-05  4.732015e-06  3.638251e-05   
-uSTNyHkde08  0.021930  2.495787e-05  8.117040e-07  2.121147e-05   
-lvK2TPBDvl4  0.000229  1.813735e-06  7.948588e-08  1.241068e-06   
-OT8lw1Rl-WM  0.000005  1.747444e-08  4.968363e-12  5.525666e-09   
-u9hauSrihYQ  0.000472  6.581184e-05  2.157791e-06  7.214768e-05   
...                ...           ...           ...           ...   
-7aXpBF2mjtg  0.000005  9.458382e-06  3.512658e-08  3.595870e-06   
-2REkk9SCRn0  0.000045  6.285003e-05  3.551395e-06  5.236510e-05   
-g4woIrtHTOc  0.000275  6.412073e-06  3.957370e-08  3.304207e-06   
-pQu3dufotPM  0.000761  1.136992e-05  4.609679e-07  7.582129e-06   
-8BbZTCdB2X4  0.006549  1.204783e-05  2.195528e-07  7.818506e-06   

                       9    ...           511           512           513  \
-AZS5cgybKcI  1.735417e-06  ...  4.330092e-05  9.821250e-07  1.839629e-04   
-uSTNyHkde08  4.280596e-07  ...  1.431625e-05  1.749882e-06  5.454943e-05   
-lvK2TPBDvl4  3.755787e-08  ...  2.261237e-07  7.088843e-10  5.419458e-08   
-OT8lw1Rl-WM  1.668432e-12  ...  1.326842e-05  1.014781e-08  5.257566e-08   
-u9hauSrihYQ  1.203631e-06  ...  2.459629e-06  2.274370e-07  1.540807e-05   
...                    ...  ...           ...           ...           ...   
-7aXpBF2mjtg  9.238269e-08  ...  2.260958e-05  7.437294e-10  3.508532e-06   
-2REkk9SCRn0  2.508292e-06  ...  7.062811e-06  2.063451e-06  3.393742e-05   
-g4woIrtHTOc  3.486264e-08  ...  5.720985e-06  1.885902e-08  1.986428e-08   
-pQu3dufotPM  2.589666e-07  ...  1.025157e-06  1.184329e-07  6.000910e-07   
-8BbZTCdB2X4  7.931755e-08  ...  4.776082e-06  1.639825e-06  1.191597e-06   

                       514           515           516           517  \
-AZS5cgybKcI  5.289807e-04  2.474351e-05  7.315379e-05  1.748715e-04   
-uSTNyHkde08  3.374542e-04  1.035530e-04  3.252637e-05  1.793257e-04   
-lvK2TPBDvl4  3.762583e-07  2.553923e-08  2.225540e-08  6.532983e-08   
-OT8lw1Rl-WM  9.533384e-08  5.398527e-10  6.021600e-08  1.187875e-08   
-u9hauSrihYQ  1.419609e-04  6.659506e-05  6.534895e-06  1.155913e-05   
...                    ...           ...           ...           ...   
-7aXpBF2mjtg  3.261856e-07  2.932347e-10  4.832601e-07  3.888806e-07   
-2REkk9SCRn0  1.259191e-04  4.296944e-06  8.703074e-03  2.638522e-05   
-g4woIrtHTOc  2.641852e-07  1.540977e-08  9.366641e-08  1.067836e-07   
-pQu3dufotPM  2.608112e-06  1.913772e-07  3.376322e-07  2.451204e-07   
-8BbZTCdB2X4  1.210299e-06  1.260052e-07  2.406209e-06  1.841089e-07   

                   518       519           520  
-AZS5cgybKcI  0.001129  0.000285  7.037500e-05  
-uSTNyHkde08  0.000465  0.001299  5.271555e-06  
-lvK2TPBDvl4  0.000013  0.000018  1.035225e-08  
-OT8lw1Rl-WM  0.000007  0.000010  7.441545e-10  
-u9hauSrihYQ  0.000170  0.000153  3.343296e-05  
...                ...       ...           ...  
-7aXpBF2mjtg  0.003454  0.000101  4.476325e-07  
-2REkk9SCRn0  0.001168  0.000189  4.278257e-05  
-g4woIrtHTOc  0.000268  0.000078  7.340961e-08  
-pQu3dufotPM  0.000166  0.000434 

#### DataSet Equilbré

In [ ]:

import pickle
import pandas as pd
# Les datasets labels
DataSetsPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/CSV/DataSets/"

train = pd.read_csv(DataSetsPath + "Train_SurSampling1.csv")
test = pd.read_csv(DataSetsPath + "Test_SurSampling1.csv")
val = pd.read_csv(DataSetsPath + "Val_SurSampling1.csv")

# Les embeddings Audio
predPath = "/content/gdrive/MyDrive/Projet_Multimedia/download/Audio_Embeddings/YAMNet/ALL_predictions_YAMNet.pkl"
with open(predPath, "rb") as fp:
    predictions = pickle.load(fp)
df_pred = pd.DataFrame.from_dict((predictions), orient='index')


# DataSet Separation
train = train.set_index('name').join(df_pred)
test = test.set_index('name').join(df_pred)
val = val.set_index('name').join(df_pred)



y_train = train.label
y_train = y_train.astype("category")
X_train = train.drop(columns=['label'])



y_test = test.label
y_test = y_test.astype("category")
X_test = test.drop(columns=['label'])

y_val = val.label
y_val = y_val.astype("category")
X_val = val.drop(columns=['label'])

In [ ]:
len(train['label'].unique())

15

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from torch.utils.data import DataLoader, TensorDataset
from transformers import AdamW
from sentence_transformers import SentenceTransformer
import torch

# Encoder les textes avec Sentence-Transformers
train_embeddings = torch.from_numpy(np.array(X_train))
test_embeddings = torch.from_numpy(np.array(X_test))
valid_embeddings = torch.from_numpy(np.array(X_val))


# Définir le modèle de classification
class ClassificationModel(torch.nn.Module):
 def __init__(self, input_size, num_labels):
  super(ClassificationModel, self).__init__()
  self.fc = torch.nn.Linear(input_size, 1024)
  self.r = torch.nn.ReLU()
  self.m = torch.nn.Dropout(p=0.4)
  self.fc1 = torch.nn.Linear(1024, 512)
  self.fc2 = torch.nn.Linear(512, 128)
  self.fc3 = torch.nn.Linear(128, num_labels)

 def forward(self, x):
  x = self.fc(x)
  x = self.r(x)
  x = self.m(x)

  x = self.fc1(x)
  x = self.r(x)
  x = self.m(x)

  x = self.fc2(x)
  x = self.r(x)
  x = self.m(x)

  x = self.fc3(x)
  x = self.r(x)
  return x

# Initialiser le modèle de classification
device = 'cuda' if torch.cuda.is_available() else 'cpu'

model = ClassificationModel(input_size=train_embeddings.size(-1), num_labels=len(train['label'].unique())).to(device)



# Définir le DataLoader
batch_size = 8
train_loader = DataLoader(TensorDataset(train_embeddings.to(device), torch.tensor(y_train.cat.codes.tolist(), dtype=torch.long).to(device)), batch_size=batch_size, shuffle=True)
test_loader = DataLoader(TensorDataset(test_embeddings.to(device) , torch.tensor(y_test.cat.codes.tolist(), dtype=torch.long).to(device)), batch_size=batch_size, shuffle=False)
valid_loader = DataLoader(TensorDataset(valid_embeddings.to(device) , torch.tensor(y_val.cat.codes.tolist(), dtype=torch.long).to(device)), batch_size=batch_size, shuffle=False)

# Définir l'optimiseur
optimizer = AdamW(model.parameters())

num_epochs = 7

# Entraîner le modèle
for epoch in range(num_epochs):
 model.train()
 total_loss = 0.0
 total_loss_valid = 0.0

 for batch in train_loader:
  embeddings, labels = batch
  optimizer.zero_grad()
  outputs = model(embeddings)
  loss = torch.nn.functional.cross_entropy(outputs, labels)
  total_loss += loss.item()
  loss.backward()
  optimizer.step()

 average_loss = total_loss / len(train_loader)
 for batch in valid_loader:
  embeddings, labels = batch
  optimizer.zero_grad()
  outputs = model(embeddings)
  loss = torch.nn.functional.cross_entropy(outputs, labels)
  total_loss_valid += loss.item()
 average_loss_valid = total_loss_valid / len(valid_loader)
 print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {average_loss}, Val_loss: {average_loss_valid}')

# Évaluer le modèle
model.eval()
all_preds = []
all_labels = []

with torch.no_grad():
 for batch in test_loader:
  embeddings, labels = batch
  outputs = model(embeddings)
  preds = torch.argmax(outputs, dim=1)
  all_preds.extend(preds.tolist())
  all_labels.extend(labels.tolist())

# Calculer la précision
accuracy = accuracy_score(all_labels, all_preds)
print(f'Accuracy: {accuracy}')

# Sauvegarder le modèle
torch.save(model.state_dict(), 'Model_with_Predictions_Son_Environnant_transformers.pth')

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


Epoch 1/7, Loss: 2.5498429995700405, Val_loss: 2.462739185988903
Epoch 2/7, Loss: 2.4369244620391015, Val_loss: 2.4283106423914433
Epoch 3/7, Loss: 2.3770067093262615, Val_loss: 2.3974392667412756
Epoch 4/7, Loss: 2.337306527413085, Val_loss: 2.386199504137039
Epoch 5/7, Loss: 2.2908172772020476, Val_loss: 2.4128258362412454
Epoch 6/7, Loss: 2.2496745491626373, Val_loss: 2.366431711614132
Epoch 7/7, Loss: 2.233742074487598, Val_loss: 2.357209274172783
Accuracy: 0.290625
